---
- name: add Hashicorp repository GPG key
  apt_key:
    url: "{{ packer_apt_key_url }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: add Hashicorp repository
  apt_repository:
    repo: "deb [arch=amd64] {{ packer_apt_url }} {{ 'focal' if ansible_distribution_version is version('20.04', '>') else ansible_distribution_release }} main"
    state: present
    filename: hashicorp_official
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: packer_apt_result

- name: ensure right permissions on apt sources list
  file:
    path: /etc/apt/sources.list.d/hashicorp_official.list
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: apt update list for new Hashicorp repository # noqa 503
  apt:
    update_cache: yes
  when: packer_apt_result.changed | bool

- name: install packer
  apt:
    name: "{{ packer_apt_package }}{{ ('=' ~ packer_version) if packer_version and packer_version != 'latest' else '' }}"
    state: "{{ 'present' if packer_version and packer_version != 'latest' and packer_state == 'latest' else packer_state }}"
